"""Run the eval harness + baseline comparison and emit docs/METRICS.md.

    PYTHONPATH=src python scripts/generate_report.py

The generated table is the single most useful artifact for a portfolio: real,
reproducible numbers with a naive-baseline contrast, not a claim.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from insightledger.config import get_settings          # noqa: E402
from insightledger.eval.baseline import run_baseline    # noqa: E402
from insightledger.eval.harness import check_gate, run_eval  # noqa: E402


def main() -> None:
    s = get_settings()
    full = run_eval(save=True)
    base = run_baseline()
    gate = check_gate(full)

    def row(name, key, fmt="{:.3f}"):
        bv = getattr(base, key)
        fv = getattr(full, key)
        return f"| {name} | {fmt.format(bv)} | {fmt.format(fv)} | {fv - bv:+.3f} |"

    md = f"""# InsightLedger — Evaluation Metrics

_Auto-generated by `scripts/generate_report.py`. Backends: `{full.backends}`._

Golden set: **{full.n} items** over synthetic SEC-style filings (single-fact
lookups, cross-page/chart reasoning, and adversarial *unanswerable* questions).

## Headline: multi-agent visual-RAG vs. naive text-RAG

| Metric | text-RAG baseline | InsightLedger | Δ |
|---|---|---|---|
{row("Retrieval recall@k", "recall_at_k")}
{row("Faithfulness (grounded)", "faithfulness")}
{row("Answer accuracy", "answer_accuracy")}
{row("Citation region IoU", "mean_citation_iou")}
{row("Hallucination rate", "hallucination_rate")}

## Full pipeline detail

- recall@k: **{full.recall_at_k:.3f}**
- faithfulness: **{full.faithfulness:.3f}**
- answer accuracy: **{full.answer_accuracy:.3f}**
- citation IoU: **{full.mean_citation_iou:.3f}**
- hallucination rate: **{full.hallucination_rate:.3f}**
- latency p50 / p95: **{full.p50_latency_ms:.1f} / {full.p95_latency_ms:.1f} ms**
- cost mean / total: **${full.mean_cost_usd:.6f} / ${full.total_cost_usd:.6f}**

## CI gate

**{'PASS' if gate.passed else 'FAIL'}** — thresholds enforced on every commit
(see `insightledger/eval/harness.py::DEFAULT_THRESHOLDS`).
{chr(10).join('- ' + f for f in gate.failures) if gate.failures else ''}

> Numbers above are on the deterministic **stub** backends so anyone can
> reproduce them with `make eval`. Swap in ColQwen + Claude + Qdrant
> (`pip install -e .[vision,llm,qdrant]`) to measure the production stack.
"""
    out = Path(__file__).resolve().parents[1] / "docs" / "METRICS.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text(md, encoding="utf-8")
    print(f"wrote {out}")
    print(f"gate: {'PASS' if gate.passed else 'FAIL'}")


if __name__ == "__main__":
    main()
